name: "Git LFS Check"

on: pull_request
permissions: {}
jobs:
  lfs-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Check Git LFS files for consistency
        run: |
          git lfs fsck
